### PR TITLE
chore: removed the old upgrade handler

### PR DESCRIPTION
**Pull request by vishal-kanna**

### CODE REVIEW

**Comment by byte-bandit** [comment]
I'm not sure the old upgrade handler is responsible here, since it's just a set of conditionals that would not be executed. But it's worth a try. We'd lose the ability to restore from an old snapshot, but I think that's no problem @taariq @verabehr ?

@vishal-kanna Did you test this in pvt test net? Setting it up with `v1.13.0`, proposing a software upgrade and successfully upgrading to a version built with these changes?

**Comment by vishal-kanna** [comment]
@byte-bandit I've tested it locally.It is working fine and i need to test it in the pvt testnet.

**Comment by byte-bandit** [comment]
@vishal-kanna Sounds good. Since this change addresses the upgrade mechanic, we need to ensure that a network will be able to upgrade successfully from `v1.13.0` to `v1.13.1`.

**Comment by taariq** [comment]
@vishal-kanna when will you have a test completed on this? We would like to cut a new release with this fix and the upgrade on CometBFT.

**Review by byte-bandit — APPROVED** [review]

**Pull request merged**
