### PR TITLE
chore: updated v0.50-upgrade branch with master

### PR DESCRIPTION
**Pull request by deepan95dev**
As there are few recent commits to master branch, which are not in v0.50.0-upgrade branch, this PR would help in merging those 2 branches and move further for cumulative fixes of all modules.

### CODE REVIEW

**Comment by byte-bandit** [comment]
Why not simply rebase the `v.50.0-upgrade` branch on `master`?

**Comment by deepan95dev** [comment]
> Why not simply rebase the `v.50.0-upgrade` branch on `master`?

With this branch we can target fixing all the module fixes as cumulative fix, including test files, util files and modules under `x/` folder. So that all tests and lints will pass.

**Comment by byte-bandit** [comment]
> > Why not simply rebase the `v.50.0-upgrade` branch on `master`?
> 
> 
> 
> With this branch we can target fixing all the module fixes as cumulative fix, including test files, util files and modules under `x/` folder. So that all tests and lints will pass.

You get the same with a rebase and a cleaner commit history?

**Comment by deepan95dev** [comment]
> > > Why not simply rebase the `v.50.0-upgrade` branch on `master`?
> > 
> > 
> > With this branch we can target fixing all the module fixes as cumulative fix, including test files, util files and modules under `x/` folder. So that all tests and lints will pass.
> 
> You get the same with a rebase and a cleaner commit history?

Since we cannot push to  v0.50.upgrade branch directly, I raised PR

**Comment by byte-bandit** [comment]
@deepan95dev Fair enough, by now there's a considerable amount of changes on the upgrade branch and keeping history of pulling in updates from master makes sense. Let's do it this way. Let me know when ready to review.

**Pull request closed without merging**
