### PR TITLE
add logs

### PR DESCRIPTION
**Pull request by webelf101**
# Related Github tickets

- a list of github issues that are relevant for this PR

# Background

_A short paragraph on test what exactly this PR solves._

# Testing completed

- [ ] _a list of actions that you've performed to ensure that this PR works as intended_
- [ ] _99% of the times you should have an item: "wrote tests"_

# Breaking changes

- [ ] I have checked my code for breaking changes
- [ ] If there are breaking changes, there is a supporting migration.

### CODE REVIEW

**Review by taariq — APPROVED** [review]
Let's see those messages! LGTM!

**Comment by taariq** [comment]
@webelf101 & @alexanderbez tests fail.

```--- FAIL: TestEndToEndTestingOfPuttingAndGettingMessagesOfTheConsensusQueue (0.00s)
    --- PASS: TestEndToEndTestingOfPuttingAndGettingMessagesOfTheConsensusQueue/it_returns_a_message_if_type_is_not_registered_with_the_queue (0.00s)
    --- PASS: TestEndToEndTestingOfPuttingAndGettingMessagesOfTheConsensusQueue/it_returns_no_messages_for_signing (0.00s)
    --- PASS: TestEndToEndTestingOfPuttingAndGettingMessagesOfTheConsensusQueue/it_sucessfully_puts_message_into_the_queue (0.00s)
    --- FAIL: TestEndToEndTestingOfPuttingAndGettingMessagesOfTheConsensusQueue/it_sucessfully_gets_message_from_the_queue (0.00s)
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method [recovered]
	panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 16 [running]:
testing.tRunner.func1.2({0xef2f00, 0x132eca0})
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1399 +0x39f
panic({0xef2f00, 0x132eca0})
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x212
reflect.valueInterface({0xf24a20?, 0xc000ce8708?, 0x12?}, 0x0?)
	/opt/hostedtoolcache/go/1.19.4/x64/src/reflect/value.go:1489 +0xd8
reflect.Value.Interface(...)
	/opt/hostedtoolcache/go/1.19.4/x64/src/reflect/value.go:1478
github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0x0?, 0xc000cdd340, {0xf24a20?, 0xc000ce8708?, 0x134ba10?}, 0xc000021900)
	/home/runner/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:615 +0xa9d
github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x1a601a8, 0xc000cdd340, {0x100cf00?, 0xc000ce86c0?, 0x1?})
	/home/runner/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:453 +0x8df
github.com/gogo/protobuf/proto.(*TextMarshaler).writeAny(0xef391a?, 0xc000cdd340, {0x105cfe0?, 0xc0000f8bf8?, 0x134ba10?}, 0xc000021300)
	/home/runner/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:606 +0x935
github.com/gogo/protobuf/proto.(*TextMarshaler).writeStruct(0x1a601a8, 0xc000cdd340, {0x1022580?, 0xc0000f8bd0?, 0x0?})
	/home/runner/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:453 +0x8df
github.com/gogo/protobuf/proto.(*TextMarshaler).Marshal(0x1a601a8, {0x132ffc0?, 0xc000ce3fb0?}, {0x13392b0?, 0xc0000f8bd0?})
	/home/runner/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:896 +0x367
github.com/gogo/protobuf/proto.(*TextMarshaler).Text(0x0?, {0x13392b0, 0xc0000f8bd0})
	/home/runner/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:908 +0x56
github.com/gogo/protobuf/proto.CompactTextString(...)
	/home/runner/go/pkg/mod/github.com/regen-network/protobuf@v1.3.3-alpha.regen.1/proto/text.go:930
github.com/palomachain/paloma/x/consensus/types.(*QueuedSignedMessage).String(0x1343bf0?)
	/home/runner/work/paloma/paloma/x/consensus/types/consensus_queue.pb.go:46 +0x2a
github.com/palomachain/paloma/x/consensus/keeper.Keeper.GetMessagesFromQueue({{0x1343bf0, 0xc000cd3c70}, {0x1333930, 0xc000cd3bf0}, {0x1333958, 0xc000cd3c00}, {{0x1343bf0, 0xc000cd3c70}, 0xc000014a30, {0x1333930, ...}, ...}, ...}, ...)
	/home/runner/work/paloma/paloma/x/consensus/keeper/concensus_keeper.go:121 +0x542
github.com/palomachain/paloma/x/consensus/keeper.Keeper.GetMessagesForSigning({{0x1343bf0, 0xc000cd3c70}, {0x1333930, 0xc000cd3bf0}, {0x1333958, 0xc000cd3c00}, {{0x1343bf0, 0xc000cd3c70}, 0xc000014a30, {0x1333930, ...}, ...}, ...}, ...)
	/home/runner/work/paloma/paloma/x/consensus/keeper/concensus_keeper.go:85 +0xbd
github.com/palomachain/paloma/x/consensus/keeper.TestEndToEndTestingOfPuttingAndGettingMessagesOfTheConsensusQueue.func5(0x0?)
	/home/runner/work/paloma/paloma/x/consensus/keeper/concensus_keeper_test.go:73 +0x133
testing.tRunner(0xc000d02ea0, 0xc000ce3f50)
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1493 +0x35f
FAIL	github.com/palomachain/paloma/x/consensus/keeper	0.080s```

**Comment by taariq** [comment]
Weird that this test didn't fail on the last run through, but now it fails.

**Comment by taariq** [comment]
@webelf101 tests still failing.

**Comment by alexanderbez** [comment]
`TestEndToEndTestingOfPuttingAndGettingMessagesOfTheConsensusQueue` PASSES for me locally (on `master`).

**Pull request merged**
