### PR TITLE
Update iavl_v0.19.3 to v0.19.4

### PR DESCRIPTION
**Pull request by taariq**
# Related Github tickets

closes: #562

# Background

_Fix to IAVL issues that blocked upgrade after Dragonberry.

# Testing completed

- [ ] Requires confirmation testing.

# Breaking changes

- [ ] No checks for breaking changes.

### CODE REVIEW

**Comment by taariq** [comment]
@tacoturtle: Any help with this?

**Comment by taariq** [comment]
@tac0turtle: Will you help us wit the failing test on the module? We are unable to proceed.

**Comment by alexanderbez** [comment]
Pushed an update with the correct approach (I think?)

**Review by tac0turtle — APPROVED** [review]
Looks good now

**Review by measure-fi — APPROVED** [review]
Would prefer the replace list were lexicographically sorted.

**Comment by alexanderbez** [comment]
> Would prefer the replace list were lexicographically sorted.

Golang determines the replace order AFAICT.

**Pull request merged**
