### PR TITLE
chore: upgrade cosmwasm to 0.40.1

### PR DESCRIPTION
**Pull request by byte-bandit**
# Related Github tickets
https://github.com/VolumeFi/paloma/issues/203

# Testing completed

- [x] _a list of actions that you've performed to ensure that this PR works as intended_
- [x] _99% of the times you should have an item: "wrote tests"_

# Breaking changes

- [x] I have checked my code for breaking changes
- [x] If there are breaking changes, there is a supporting migration.

### CODE REVIEW

**Review by taariq — APPROVED** [review]
LGTM!

**Comment by byte-bandit** [comment]
@ToasterTheBrave

There are quite a few breaking changes in the upgrade to `0.40.1`:

- https://github.com/CosmWasm/cosmwasm/blob/main/CHANGELOG.md
- https://github.com/cosmos/ibc-go/blob/v7.0.0/docs/migrations/v6-to-v7.md
- https://github.com/cosmos/cosmos-sdk/blob/main/UPGRADING.md#v047x

As far as I can tell, Paloma is already ahead of most of what's required though. I'm not sure yet about chain migrations though.

**Comment by ToasterTheBrave** [comment]
@byte-bandit It's going to come down to testing.  You need to test the functionality around wasm and ensure jobs still execute as expected on the new code

**Comment by ToasterTheBrave** [comment]
To your question on migrations.  We should test an upgrade to ensure things work correctly.

**Review by ToasterTheBrave — CHANGES_REQUESTED** [review]
Tossing in a review to prevent merging.  It sounds like this hasn't been fully tested yet.

**Comment by byte-bandit** [comment]
@ToasterTheBrave 

I used the current release (`v.1.4.0`) as reference to make sure `WASM` contracts compiled and executed as expected. Then, I upgraded my local test net to this branch and repeated the test. You can find the successful `submit_logic_call()` transaction here: https://bscscan.com/tx/0x368fe464b0d4ec4614a840f3c217331dffb417896a413ae429d0c9c25d10ef70

As far as I can tell, everything works as expected.

**Comment by ToasterTheBrave** [comment]
A couple small things:
1. Is that the right tx showing success from the changes?  It's from 15 hours ago.
2. We need to update the readme for the new version of wasmvm

**Comment by byte-bandit** [comment]
@ToasterTheBrave 

1. Yes, I was pulling a late night to get it in yesterday, that's when I finished testing.
2. Good point, I will touch the readme to reflect the changes. 
3. I'll also take a look at test net scripts, I think they pull in some specific version as well.

**Review by ToasterTheBrave — APPROVED** [review]

**Comment by byte-bandit** [comment]
See https://github.com/palomachain/private-testnet/pull/36

**Pull request merged**
