### PR TITLE
feat: Custom Tx Prioritization

### PR DESCRIPTION
**Pull request by alexanderbez**
closes: #807

## Changelog

- Set explicit ABCI handlers
- Set explicit app mempool
- Implement custom mempool
- Configure mempool with custom tx prioritization

### CODE REVIEW

**Comment by taariq** [comment]
Here is the DRAFT proposal of message prioritization @alexanderbez:

| Transaction Type  | Prioritization Number | Reasoning |
| ------------- | ------------- | ------------- |
| ValsetUpdate Transaction | 1  | Valset Updates are transactions to target chains Compass contract with signature of the validator set |
| ExecuteJob Transaction | 2  | ExecuteJobs that are queued for delivery of cross-chain messages |
| Attest Messages | 3  | Check and Process Attestation of all Pigeon messages.  |

**Comment by taariq** [comment]
How you like me now @alexanderbez https://github.com/palomachain/paloma/pull/808#issuecomment-1520806940

**Comment by taariq** [comment]
Don't forget the linter.

**Comment by taariq** [comment]
> > Don't forget the linter.
> 
> You mean gci? I've never seen that before. If it's a linting target, please add it to the makefile so devs can easily run it :)
https://github.com/palomachain/paloma/blob/master/Makefile#L111 for gci. Right?

**Comment by alexanderbez** [comment]
No, that's golangci-lint ;-)

**Comment by taariq** [comment]
Let me crawl back into my cave and figure that out! Thank you or the guidance!

**Comment by alexanderbez** [comment]
Ok, I was partially wrong on the linter. The golangci-lint has the gci linter enabled, so it's bundled automatically. I added a fix make target to automatically fix errors.

**Review by taariq — APPROVED** [review]
And now we have lint fixes with Custom mempools. LFG!

**Pull request merged**
