### PR TITLE
chore: bump to go1.19

### PR DESCRIPTION
**Pull request by alexanderbez**
closes: #584
closes: #583

**NOTE:  Using wasm v0.30 requires IBC v4.**
ref: https://github.com/cosmos/ibc-go/blob/v4.2.0/docs/migrations/v3-to-v4.md

### CODE REVIEW

**Comment by alexanderbez** [comment]
Using wasm v0.30 requires IBC v4.

**Comment by taariq** [comment]
@measure-fi will you give a review before we merge?

**Comment by taariq** [comment]
@alexanderbez I notice autobuild has been running for aver an hour. Is something up there?

**Comment by alexanderbez** [comment]
I'm not sure. I'm not familiar with that CI job. But the binary builds fine for me locally.

**Comment by taariq** [comment]
@verabehr will you please merge this PR after you approve/merge the logs?

**Comment by measure-fi** [comment]
That's the cosmwasm linter for things like floating point and map iteration in the interpreter path. It's done this a couple times we should probably add a timeout.

**Comment by taariq** [comment]
Merging

**Pull request merged**
