### PR TITLE
remove logs

### PR DESCRIPTION
**Pull request by webelf101**
# Related Github tickets

- a list of github issues that are relevant for this PR

# Background

_A short paragraph on test what exactly this PR solves._

# Testing completed

- [ ] _a list of actions that you've performed to ensure that this PR works as intended_
- [ ] _99% of the times you should have an item: "wrote tests"_

# Breaking changes

- [ ] I have checked my code for breaking changes
- [ ] If there are breaking changes, there is a supporting migration.

### CODE REVIEW

**Review by verabehr — CHANGES_REQUESTED** [review]
the tests fail, but also can you change these to level "Debug" instead of "Info"?

**Comment by verabehr** [comment]
@webelf101 will you please confirm that it NOT possible to keep these logs as `Debug`? I'd rather keep them as that then removing them completely.

**Comment by verabehr** [comment]
Please ensure that both logs that are mentioned in the original ticket are level `debug`. https://github.com/palomachain/paloma/issues/624 Thanks @webelf101

**Review by taariq — APPROVED** [review]
LGTM!

**Comment by taariq** [comment]
@webelf101 changes are requested. When will these be closed?

**Review by verabehr — APPROVED** [review]

**Pull request merged**
