### PR TITLE
update logs

### PR DESCRIPTION
**Pull request by webelf101**
# Related Github tickets

- a list of github issues that are relevant for this PR

# Background

_A short paragraph on test what exactly this PR solves._

# Testing completed

- [ ] _a list of actions that you've performed to ensure that this PR works as intended_
- [ ] _99% of the times you should have an item: "wrote tests"_

# Breaking changes

- [ ] I have checked my code for breaking changes
- [ ] If there are breaking changes, there is a supporting migration.

### CODE REVIEW

**Review by verabehr — APPROVED** [review]

**Comment by taariq** [comment]
@verabehr & @webelf101 we'll need to remove the printfs for this PR so that we don't make the logs overly noisy on master.

**Comment by verabehr** [comment]
Is it possible to keep them and change the level  to "debug" instead? They
might be useful in the future.

**Comment by taariq** [comment]
No. Those are print statements, no logging. It will print out those messages on the server logs.

**Comment by taariq** [comment]
@webelf101 am I correct here?

**Pull request merged**
